domain: security-metadata.canonical.com

image: prod-comms.docker-registry.canonical.com/security-metadata.canonical.com

env:
  - name: DATABASE_URL
    secretKeyRef:
      key: database_url
      name: usn-db-url

  - name: SENTRY_DSN
    value: https://0293bb7fc3104e56bafd2422e155790c@sentry.is.canonical.com//13

# Overrides for production
production:
  replicas: 5

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
